### ISSUE TITLE
模板的问题

### ISSUE THREAD

**Issue by moyels** [feimenggo/fdroid#1]
好像库文件的包名改了，导致用模板创建了之后import的包名路径是错误的，需要修改一下应该。
还有就是我觉得可以把activity，contract，presenter分别放在不同的文件夹下。我自己修改好了模板在用了，希望老哥也能改一下，更好用我就下载新的。

**Comment by feimenggo** [comment]
好的，我会更新一下模板。确实推荐将activity，contract，presenter分别放在不同包下，近期我会下更新DEMO。

**Comment by feimenggo** [comment]
您好！MVP模板文件已经更新了。Demo项目使用了合理的分包，并且添加了网络请求的例子。

**Comment by moyels** [comment]
好的、多谢老哥了。哈哈
